# Generated by Django 3.0.8 on 2020-08-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(default='apellido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='nombre', max_length=255),
            preserve_default=False,
        ),
    ]
