# Generated by Django 3.0.8 on 2020-08-27 19:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200818_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biografia',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_moder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='apellido',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.FileField(default='perfil.png', upload_to='home/photos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=55),
        ),
    ]
