# Generated by Django 3.0.8 on 2020-08-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200827_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biografia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
