# Generated by Django 3.0.8 on 2020-08-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='Pregunta',
            new_name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='Respuesta',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='respuesta',
            field=models.ManyToManyField(related_name='respuesta_related_r', to='pregunta.Respuesta'),
        ),
    ]
