# Generated by Django 3.0.8 on 2020-08-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0002_auto_20200817_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='title',
            field=models.CharField(default='z ', max_length=255),
            preserve_default=False,
        ),
    ]
