# Generated by Django 3.0.8 on 2020-08-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0003_pregunta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='url',
        ),
    ]
