# Generated by Django 3.0.8 on 2020-08-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0004_remove_pregunta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='eshijo',
            field=models.BooleanField(default=False),
        ),
    ]
